//User login
export const ADMIN_LOGIN_START = "ADMIN_LOGIN_START";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILURE = "ADMIN_LOGIN_FAILURE";

//product Create 
export const PRODUCT_CREATE_START = "PRODUCT_CREATE_START";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAILURE = "PRODUCT_CREATE_FAILURE";

//get products 
export const PRODUCT_FETCH_START = "PRODUCT_FETCH_START";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAILURE = "PRODUCT_FETCH_FAILURE";

//get single product 
export const SINGLE_PRODUCT_FETCH_START = "SINGLE_PRODUCT_FETCH_START";
export const SINGLE_PRODUCT_FETCH_SUCCESS = "SINGLE_PRODUCT_FETCH_SUCCESS";
export const SINGLE_PRODUCT_FETCH_FAILURE = "SINGLE_PRODUCT_FETCH_FAILURE";

//update product
export const PRODUCT_UPDATE_START = "PRODUCT_UPDATE_START";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAILURE = "PRODUCT_UPDATE_FAILURE";

//delete product
export const PRODUCT_DELETE_START = "PRODUCT_DELETE_START";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAILURE = "PRODUCT_DELETE_FAILURE";


